### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [pvorb/platon#54]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/de/vorb/platon/security/DatabaseSecretKeyProvider.java: Line number => 62: API name => KeyGenerator:<BR> File name => src/main/java/de/vorb/platon/web/api/common/CommentConverter.java: Line number => 38: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR> File name => src/main/java/de/vorb/platon/security/DatabaseSecretKeyProvider.java: Line number => 71: API name => SecretKeySpec:<BR> File name => src/main/java/de/vorb/platon/security/DatabaseSecretKeyProvider.java: Line number => 70: API name => SecretKeySpec:<BR> File name => src/main/java/de/vorb/platon/security/HmacSignatureTokenValidator.java: Line number => 51: API name => Mac:Operation on object of type javax.crypto.Mac object not completed. Expected call to update, doFinal<BR>

**Comment by pvorb** [comment]
Closing this issue because it is auto-generated and I can't make much sense of it.
